package com.examind.backend.common.audit;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    REGISTER,
    EXAM_CREATED,
    EXAM_UPDATED,
    EXAM_DELETED,
    EXAM_PUBLISHED,
    EXAM_UNPUBLISHED,
    QUESTION_CREATED,
    QUESTION_UPDATED,
    QUESTION_DELETED,
    SUBMISSION_STARTED,
    ANSWER_SAVED,
    SUBMISSION_COMPLETED,
    AI_EVALUATED,
    EVALUATION_APPROVED,
    EVALUATION_OVERRIDDEN,
    USER_BLOCKED,
    USER_UNBLOCKED,
    FILE_UPLOADED
}
